Repository aantron/dream, pull requests merged in 2024-10, with the labels that each got.

#352 CI: use Ubuntu 22.04
  .github/workflows/test.yml
Labels: 🤷‍♀️ upstream

#330 Examples: add w-mlx
  example/w-mlx/README.md
  example/w-mlx/dune
  example/w-mlx/dune-project
  example/w-mlx/dune-workspace
  example/w-mlx/mlx.mlx
  example/w-mlx/w-mlx.opam
Labels: 📚 docs

#323 Add dream-html example
  example/7-template/README.md
  example/README.md
  example/w-dream-html/README.md
  example/w-dream-html/dune
  example/w-dream-html/dune-project
  example/w-dream-html/html.ml
  example/w-dream-html/w-dream-html.opam
  example/z-playground/server/sync.sh
Labels: 📚 docs

#353 CI: try dune-cache
  .github/workflows/test.yml
Labels: 🧱 ci
